version: "3.6"
services:
  broadlinkmanager:
    image: techblog/broadlinkmanager
    container_name: broadlinkmanager
    restart: unless-stopped
    volumes:
      - ./broadlinkmanager:/opt/broadlinkmanager/data
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PORT:-7020}:7020"
    environment:
      - ENABLE_GOOGLE_ANALYTICS=False
